USE MASTER
CREATE DATABASE INSTITUTO

GO 
USE INSTITUTO

CREATE TABLE USUARIOS(
ID INT IDENTITY (1,1)PRIMARY KEY,
USUARIO VARCHAR(100),
CLAVE VARCHAR (100),
TIPO VARCHAR (50))

INSERT INTO USUARIOS VALUES ('PELON','REY','ADMIN')

CREATE TABLE ESTUDIANTE(
ID INT IDENTITY(100001,1)PRIMARY KEY,
NOMBRES VARCHAR (100),
APELLIDOS VARCHAR (100),
DNI CHAR(8),
EDAD INT,
DIRECCION VARCHAR (100),
DISTRITO VARCHAR (100),
FECHA DATE,
FOTO IMAGE )
GO 


--grabar
CREATE PROCEDURE GRABA_ESTUDIANTES
	@NOMBRES varchar(100),
	@APELLIDOS varchar(100),
	@DNI char(8),
	@EDAD int,
	@DIRECCION varchar(100),
	@DISTRITO varchar(100),
	@FECHA date,
	@FOTO image
AS
BEGIN
	insert into ESTUDIANTE(NOMBRES,APELLIDOS,DNI,EDAD,DIRECCION,DISTRITO,FECHA,FOTO)	values 
	(@NOMBRES,@APELLIDOS,@DNI,@EDAD,@DIRECCION,@DISTRITO,@FECHA,@FOTO)
END
GO

--eliminar
create procedure BORRAR_ESTUDIANTE
@ID INT
as
BEGIN
DELETE FROM ESTUDIANTE WHERE ID = @ID;
END

--editar
CREATE PROCEDURE EDITA_ESTUDIANTES
	@NOMBRES varchar(100),
	@APELLIDOS varchar(100),
	@DNI char(8),
	@EDAD int,
	@DIRECCION varchar(100),
	@DISTRITO varchar(100),
	@FOTO image
AS
BEGIN
    UPDATE ESTUDIANTE SET NOMBRES=@NOMBRES,APELLIDOS=@APELLIDOS,EDAD=@EDAD,
    DIRECCION=@DIRECCION,DISTRITO=@DISTRITO,FOTO=@FOTO WHERE @NOMBRES = @NOMBRES;

END
GO








